Add Laravel 9 and PHP 8.1 support
daniel-de-wit/lighthouse-sanctum pull request #72
Opened 2022-02-24 12:18 UTC by wimski

2022-02-25 07:44 UTC, daniel-de-wit requested changes
Thanks again for taking the time to improve this package @wimski, much appreciated.

2022-02-25 08:24 UTC, wimski commented on composer.json
> +        "thecodingmachine/safe": "^2.0"
Unfortunately it can't. I spent quite some time trying to get prefer-lowest with PHP 8.1 to play nice. `thecodingmachine/safe` is a sub dependency of quite some packages (Lighthouse itself amongst others) and `^1.0` doesn't work with PHP 8.1, so I had to place a hard constraint on it myself.

I'm just curious to see if the Github actions will pass for all possible combinations 😬

2022-02-25 09:02 UTC, daniel-de-wit approved these changes

2022-02-25 10:03 UTC, wimski commented
@daniel-de-wit hmm, this prefer-lowest thing is going to be a real issue between 7.4 and 8.1 🤔

2022-02-25 10:11 UTC, daniel-de-wit commented
@wimski We might as well drop support for php 7.4 as [Laravel 9 requires php 8.0.2](https://laravel.com/docs/9.x/upgrade#updating-dependencies) and tag this as a major version.

2022-03-06 00:35 UTC, andruu commented
Any updates on merging this PR?

2022-03-06 07:57 UTC, merged